package com.joesharp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@CrossOrigin
public class AuthorController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AuthorRepository authorRepository;


    @RequestMapping("/serverName")
    String getServerName() {
        return "Arnold Rimmer";
    }

    @GetMapping("/")
    public Iterable<Author> getAll() {
        return authorRepository.findAll();
    }

    @GetMapping("/author")
    public Author getById(@RequestParam(value="id") Integer id) {
        return authorRepository.findById(id).orElse(null);
    }
}
